import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

/**
 * `src/data/docs-index.json` is a build artifact (generated by the `prebuild`
 * script, git-ignored) that `DocsSearchBar` imports statically. Without it,
 * Vite fails to resolve the import and every suite touching the docs UI dies
 * at transform time.
 *
 * CI happens to run `npm run build` before `npm run test`, which hid this —
 * but `npm ci && npm test` on a fresh clone did not work. Generating the index
 * here makes the test command self-sufficient.
 */
export default async function setup() {
  const indexFile = path.resolve(process.cwd(), "src/data/docs-index.json");
  if (fs.existsSync(indexFile)) return;

  const generator = path.resolve(
    process.cwd(),
    "scripts/generate-docs-index.mjs",
  );
  await import(pathToFileURL(generator).href);
}
