/**
 * Diagram pipeline runner.
 *
 *   npm run diagrams        regenerate every committed SVG
 *   npm run diagrams:check  fail when a committed SVG is stale (CI)
 *
 * Each `scripts/diagrams/*.py` file is one diagram; running it writes
 * `public/diagrams/<basename>.svg`. `helpers.py` and `_`-prefixed modules are
 * support files rather than diagrams.
 *
 * The check compares the `dg-source-sha256` stamp inside the committed SVG
 * with a freshly generated one instead of diffing SVG bytes: Graphviz layout
 * changes between releases, so a byte diff would report false drift every time
 * the runner image upgrades Graphviz.
 */
import { spawnSync } from "child_process";
import fs from "fs";
import os from "os";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ROOT = path.resolve(__dirname, "../..");
const SOURCE_DIR = __dirname;
const OUTPUT_DIR = path.resolve(ROOT, "public/diagrams");

const SUPPORT_FILES = new Set(["helpers.py"]);
const STAMP_RE = /dg-source-sha256:\s*([0-9a-f]{64})/;

const check = process.argv.slice(2).includes("--check");

interface Diagram {
  name: string;
  source: string;
}

function diagramSources(): Diagram[] {
  return fs
    .readdirSync(SOURCE_DIR)
    .filter(
      (file) =>
        file.endsWith(".py") && !file.startsWith("_") && !SUPPORT_FILES.has(file),
    )
    .sort()
    .map((file) => ({
      name: path.basename(file, ".py"),
      source: path.join(SOURCE_DIR, file),
    }));
}

function pythonBin(): string {
  for (const bin of ["python3", "python"]) {
    if (spawnSync(bin, ["--version"], { stdio: "ignore" }).status === 0) {
      return bin;
    }
  }
  throw new Error("no python3 (or python) interpreter found on PATH");
}

function generate(diagram: Diagram, outDir: string): void {
  const result = spawnSync(pythonBin(), [diagram.source], {
    cwd: ROOT,
    env: { ...process.env, DIAGRAMS_OUT_DIR: outDir },
    encoding: "utf8",
  });
  if (result.status !== 0) {
    throw new Error(
      (result.stderr || result.stdout || "unknown error").trim(),
    );
  }
}

function stampOf(file: string): string | null {
  if (!fs.existsSync(file)) return null;
  return STAMP_RE.exec(fs.readFileSync(file, "utf8"))?.[1] ?? null;
}

const diagrams = diagramSources();

if (diagrams.length === 0) {
  console.error("No diagram sources found in scripts/diagrams.");
  process.exit(1);
}

if (!check) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  for (const diagram of diagrams) {
    generate(diagram, OUTPUT_DIR);
    console.log(`  public/diagrams/${diagram.name}.svg`);
  }
  console.log(`Generated ${diagrams.length} diagram(s).`);
} else {
  const scratch = fs.mkdtempSync(path.join(os.tmpdir(), "diagrams-check-"));
  const stale: string[] = [];
  try {
    for (const diagram of diagrams) {
      try {
        generate(diagram, scratch);
      } catch (error) {
        stale.push(`  ${diagram.name}: generator failed - ${(error as Error).message}`);
        continue;
      }
      const generated = stampOf(path.join(scratch, `${diagram.name}.svg`));
      const committed = stampOf(path.join(OUTPUT_DIR, `${diagram.name}.svg`));
      if (!generated) {
        stale.push(`  ${diagram.name}: generated SVG is missing its source stamp`);
      } else if (!committed) {
        stale.push(
          `  ${diagram.name}: public/diagrams/${diagram.name}.svg is missing or was not generated by this pipeline`,
        );
      } else if (generated !== committed) {
        stale.push(
          `  ${diagram.name}: source changed since public/diagrams/${diagram.name}.svg was generated`,
        );
      }
    }
  } finally {
    fs.rmSync(scratch, { recursive: true, force: true });
  }

  if (stale.length > 0) {
    console.error("Diagram SVG drift detected:");
    console.error(stale.join("\n"));
    console.error("\nRun `npm run diagrams` and commit the result.");
    process.exit(1);
  }
  console.log(`Diagrams up to date (${diagrams.length} checked).`);
}
